apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: api-base

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

labels:
- includeSelectors: true
  pairs:
    app: tenant-config-api
    app.kubernetes.io/name: tenant-config-api
    app.kubernetes.io/part-of: multi-tenant-logging
    app.kubernetes.io/component: api