FROM registry.fedoraproject.org/fedora:42

# Install Vector
RUN dnf update -y && \
    export ARCH=$(uname -m); \
    rpm -i https://yum.vector.dev/stable/vector-0/${ARCH}/vector-0.48.0-1.${ARCH}.rpm && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Switch to non-root user
USER vector

# Set working directory
WORKDIR /var/lib/vector

# Default entrypoint for Vector
ENTRYPOINT ["vector"]

# Default command shows help
CMD ["--help"]