apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - ../../openshift-base

# Patch the service account with IAM role annotation
patches:
  - path: service-account-patch.yaml
    target:
      kind: ServiceAccount
      name: vector-logs
  - path: daemonset-patch.yaml
    target:
      kind: DaemonSet
      name: vector-logs
  - path: imagestream-patch.yaml
    target:
      kind: ImageStream
      name: collector

