apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config-api-config
  namespace: logging
data:
  TENANT_CONFIG_TABLE: "integration-test-tenant-configs"
  AWS_REGION: "us-east-1"
  RUNNING_IN_K8S: "false"
  PSK_SECRET_NAME: ""
