apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-config-api
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: api
        image: tenant-config-api:github-actions
        env:
        # Add integration test specific environment variables
        - name: AWS_ENDPOINT_URL_DYNAMODB
          value: "http://dynamodb-local:8000"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"