AWSTemplateFormatVersion: '2010-09-09'
Description: 'Core infrastructure for multi-tenant logging - S3, DynamoDB, KMS, and IAM'

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues: [production, staging, development]
    Description: Environment name

  ProjectName:
    Type: String
    Default: multi-tenant-logging
    Description: Name of the project for resource naming

  EksOidcIssuer:
    Type: String
    Default: ""
    Description: OIDC issuer URL for the EKS cluster (without https://)

  S3StandardIADays:
    Type: Number
    Default: 30
    MinValue: 1
    Description: Days after which to transition S3 objects to Standard-IA

  S3GlacierDays:
    Type: Number
    Default: 90
    MinValue: 1
    Description: Days after which to transition S3 objects to Glacier

  S3DeepArchiveDays:
    Type: Number
    Default: 365
    MinValue: 1
    Description: Days after which to transition S3 objects to Deep Archive

  S3LogRetentionDays:
    Type: Number
    Default: 2555
    MinValue: 1
    Description: Number of days to retain logs in S3

  EnableS3IntelligentTiering:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable S3 Intelligent Tiering for cost optimization

  EnableS3Encryption:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable S3 server-side encryption

  RandomSuffix:
    Type: String
    Description: Random suffix for unique resource naming (generated by deploy script)
    AllowedPattern: '^[a-f0-9]{8}$'
    ConstraintDescription: Must be an 8-character hexadecimal string

Conditions:
  HasEksOidcIssuer: !Not [!Equals [!Ref EksOidcIssuer, ""]]
  IsS3IntelligentTieringEnabled: !Equals [!Ref EnableS3IntelligentTiering, "true"]
  IsS3EncryptionEnabled: !Equals [!Ref EnableS3Encryption, "true"]

Resources:

  # KMS Key for encryption (conditional)
  LoggingKMSKey:
    Type: AWS::KMS::Key
    Condition: IsS3EncryptionEnabled
    Properties:
      Description: KMS key for multi-tenant logging encryption
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow use of the key for S3
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
          - Sid: Allow use of the key for Lambda
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
      EnableKeyRotation: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-kms-key'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

  LoggingKMSKeyAlias:
    Type: AWS::KMS::Alias
    Condition: IsS3EncryptionEnabled
    Properties:
      AliasName: !Sub 'alias/${ProjectName}-${Environment}-logging'
      TargetKeyId: !Ref LoggingKMSKey

  # Central S3 Bucket for log storage
  CentralLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-central-${RandomSuffix}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [IsS3EncryptionEnabled, 'aws:kms', 'AES256']
              KMSMasterKeyID: !If [IsS3EncryptionEnabled, !Ref LoggingKMSKey, !Ref 'AWS::NoValue']
            BucketKeyEnabled: !If [IsS3EncryptionEnabled, true, false]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: LogRetentionAndTransition
            Status: Enabled
            Transitions:
              - TransitionInDays: !Ref S3StandardIADays
                StorageClass: STANDARD_IA
              - TransitionInDays: !Ref S3GlacierDays
                StorageClass: GLACIER
              - TransitionInDays: !Ref S3DeepArchiveDays
                StorageClass: DEEP_ARCHIVE
            ExpirationInDays: !Ref S3LogRetentionDays
          - Id: IntelligentTiering
            Status: !If [IsS3IntelligentTieringEnabled, Enabled, Disabled]
            Transitions:
              - TransitionInDays: 1
                StorageClass: INTELLIGENT_TIERING
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref LogDeliveryTopic
            Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: Suffix
                    Value: .gz
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-central-logging'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation


  # SNS topic for log delivery notifications
  LogDeliveryTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-log-delivery'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

  # SNS topic policy to allow S3 to publish messages
  LogDeliveryTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref LogDeliveryTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowS3Publish
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref LogDeliveryTopic
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId
              ArnEquals:
                'aws:SourceArn': !Sub 'arn:aws:s3:::${ProjectName}-${Environment}-central-${RandomSuffix}'



  # S3 Access Log Group
  S3AccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/s3/${ProjectName}-${Environment}-access'
      RetentionInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

  # DynamoDB Table for tenant configurations
  TenantConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-tenant-configs'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tenant_id
          AttributeType: S
        - AttributeName: account_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: tenant_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: AccountIdIndex
          KeySchema:
            - AttributeName: account_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: !If [IsS3EncryptionEnabled, KMS, !Ref 'AWS::NoValue']
        KMSMasterKeyId: !If [IsS3EncryptionEnabled, !Ref LoggingKMSKey, !Ref 'AWS::NoValue']
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-tenant-configs'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

  # IAM Role for Vector (EKS Service Account)
  VectorRole:
    Type: AWS::IAM::Role
    Condition: HasEksOidcIssuer
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-vector-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/${EksOidcIssuer}'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                ${EksOidcIssuer}:sub: 'system:serviceaccount:logging:vector-logs'
                ${EksOidcIssuer}:aud: 'sts.amazonaws.com'
      Policies:
        - PolicyName: VectorS3AssumeRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: !GetAtt CentralS3WriterRole.Arn
              - Effect: Allow
                Action:
                  - sts:TagSession
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

  # Central S3 Writer Role for cross-account S3 access
  CentralS3WriterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-central-s3-writer-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3WriterPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub '${CentralLoggingBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - !GetAtt CentralLoggingBucket.Arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt LoggingKMSKey.Arn
                Condition:
                  StringEquals:
                    'kms:ViaService': !Sub 's3.${AWS::Region}.amazonaws.com'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

  # Managed Policy for Vector agents to assume S3 writer role
  VectorAssumeRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${ProjectName}-${Environment}-vector-assume-role-policy'
      Description: 'Policy allowing Vector agents to assume the central S3 writer role'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: !GetAtt CentralS3WriterRole.Arn

  # IAM Role for Log Distributor Lambda
  LogDistributorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'ROSA-CentralLogDistributionRole-${RandomSuffix}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      Policies:
        - PolicyName: LogDistributorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:BatchGetItem
                Resource: !GetAtt TenantConfigTable.Arn
              - Effect: Allow
                Action:
                  - dynamodb:Query
                Resource: !Sub '${TenantConfigTable.Arn}/index/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${CentralLoggingBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: 'arn:aws:iam::*:role/CustomerLogDistribution'
                Condition:
                  StringEquals:
                    'sts:ExternalId': !Ref 'AWS::AccountId'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt LoggingKMSKey.Arn
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

  # IAM Role for DLQ Processor Lambda
  DLQProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-dlq-processor-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      Policies:
        - PolicyName: DLQProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt TenantConfigTable.Arn
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${Environment}-*'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt LoggingKMSKey.Arn
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: cloudformation

Outputs:
  CentralLoggingBucketName:
    Description: Name of the central logging S3 bucket
    Value: !Ref CentralLoggingBucket
    Export:
      Name: !Sub '${AWS::StackName}-CentralLoggingBucketName'
  CentralLoggingBucketArn:
    Description: ARN of the central logging S3 bucket
    Value: !GetAtt CentralLoggingBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CentralLoggingBucketArn'

  TenantConfigTableName:
    Description: Name of the tenant configuration DynamoDB table
    Value: !Ref TenantConfigTable
    Export:
      Name: !Sub '${AWS::StackName}-TenantConfigTableName'

  TenantConfigTableArn:
    Description: ARN of the tenant configuration DynamoDB table
    Value: !GetAtt TenantConfigTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TenantConfigTableArn'

  # SNS Outputs
  LogDeliveryTopicArn:
    Description: ARN of the log delivery SNS topic
    Value: !Ref LogDeliveryTopic
    Export:
      Name: !Sub '${AWS::StackName}-LogDeliveryTopicArn'

  # KMS Outputs (conditional)
  KMSKeyId:
    Description: KMS key ID for encryption
    Value: !If [IsS3EncryptionEnabled, !Ref LoggingKMSKey, '']
    Export:
      Name: !Sub '${AWS::StackName}-KMSKeyId'

  KMSKeyArn:
    Description: KMS key ARN for encryption
    Value: !If [IsS3EncryptionEnabled, !GetAtt LoggingKMSKey.Arn, '']
    Export:
      Name: !Sub '${AWS::StackName}-KMSKeyArn'

  VectorRoleArn:
    Description: ARN of the Vector IAM role
    Value: !If [HasEksOidcIssuer, !GetAtt VectorRole.Arn, 'NONE']
    Export:
      Name: !Sub '${AWS::StackName}-VectorRoleArn'

  CentralS3WriterRoleArn:
    Description: ARN of the Central S3 Writer IAM role
    Value: !GetAtt CentralS3WriterRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CentralS3WriterRoleArn'

  VectorAssumeRolePolicyArn:
    Description: ARN of the managed policy for Vector agents to assume S3 writer role
    Value: !Ref VectorAssumeRolePolicy
    Export:
      Name: !Sub '${AWS::StackName}-VectorAssumeRolePolicyArn'

  LogDistributorRoleArn:
    Description: ARN of the log distributor Lambda IAM role
    Value: !GetAtt LogDistributorRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LogDistributorRoleArn'

  CentralLogDistributionRoleArn:
    Description: ARN of the central log distribution role (same as LogDistributorRole)
    Value: !GetAtt LogDistributorRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CentralLogDistributionRoleArn'

  DLQProcessorRoleArn:
    Description: ARN of the DLQ processor Lambda IAM role
    Value: !GetAtt DLQProcessorRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DLQProcessorRoleArn'

  RandomSuffix:
    Description: Random suffix used for resource naming
    Value: !Ref RandomSuffix
    Export:
      Name: !Sub '${AWS::StackName}-RandomSuffix'