AWSTemplateFormatVersion: '2010-09-09'
Description: 'Customer-deployed logging infrastructure for multi-tenant logging pipeline cross-account access'

Parameters:
  CentralLogDistributionRoleArn:
    Type: String
    Description: 'ARN of the central log distribution role (provided by log service provider)'
    AllowedPattern: '^arn:aws:iam::[0-9]{12}:role/ROSA-CentralLogDistributionRole-[a-f0-9]{8}$'
    ConstraintDescription: 'Must be a valid IAM role ARN matching pattern: arn:aws:iam::ACCOUNT:role/ROSA-CentralLogDistributionRole-XXXXXXXX'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Cross-Account Access"
        Parameters:
          - CentralLogDistributionRoleArn
    ParameterLabels:
      CentralLogDistributionRoleArn:
        default: "Central Log Distribution Role ARN"

Resources:
  # IAM role for cross-account log delivery
  CustomerLogDistributionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'CustomerLogDistribution'
      Description: 'Customer-side role for cross-account log delivery'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref CentralLogDistributionRoleArn
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudWatchLogsDeliveryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Allow describing any log groups (Vector needs this for healthcheck)
              - Sid: DescribeAnyLogGroups
                Effect: Allow
                Action:
                  - 'logs:DescribeLogGroups'
                Resource: '*'
              - Sid: CreateAndManageLogGroupsAndStreams
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutRetentionPolicy'
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ROSA/cluster-logs/*'
              - Sid: PutLogEvents
                Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ROSA/cluster-logs/*:log-stream:*'
      Tags:
        - Key: 'Purpose'
          Value: 'CrossAccountLogDelivery'
        - Key: 'ManagedBy'
          Value: 'CloudFormation'
        - Key: 'DeployedBy'
          Value: 'Customer'

Outputs:
  CustomerLogDistributionRoleArn:
    Description: 'ARN of the customer log distribution role - provide this to the log service provider'
    Value: !GetAtt CustomerLogDistributionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CustomerLogDistributionRoleArn'

  HandshakeInformation:
    Description: 'Information to provide to the log service provider for setup'
    Value: !Sub |
      Customer Account ID: ${AWS::AccountId}
      Customer Log Distribution Role ARN: ${CustomerLogDistributionRole.Arn}
      Target Region: ${AWS::Region}
      
      Please provide this information to your log service provider to complete the setup.
