apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: processor
spec:
  tags:
  - name: main
    from:
      kind: DockerImage
      name: public.ecr.aws/d1w4s4o1/rosa-logrouter/processor:dev
