apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - ../base
  - scc.yaml
  - imagestream.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: log-processor