apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
  namespace: logging
spec:
  template:
    spec:
      containers:
      - name: processor
        image: log-processor:github-actions
        imagePullPolicy: Never
        env:
        # Integration test specific environment variables
        - name: AWS_ENDPOINT_URL_S3
          value: "http://minio:9000"
        - name: AWS_ENDPOINT_URL_DYNAMODB
          value: "http://dynamodb-local:8000"
        - name: AWS_ACCESS_KEY_ID
          value: "testadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "testadmin"
        - name: SQS_QUEUE_URL
          value: "dummy-sqs-url"
        - name: TENANT_CONFIG_TABLE
          value: "integration-test-tenant-configs"
        - name: CENTRAL_LOG_DISTRIBUTION_ROLE_ARN
          value: "arn:aws:iam::123456789012:role/test-role"
        - name: S3_BUCKET_NAME
          value: "test-logs"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"