{
 "title": "Hypershift Log Forwarding",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "tenant", "query": { "query": "label_values(tenant)" } }
  ]
 },
 "panels": [
  {
   "title": "Lamba Invocations (by region)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(account, region) (aws_lambda_invocations_sum{function_name=~\".*log-distributor\"})",
     "legendFormat": "{{region}} / {{account}}"
    }
   ]
  },
  {
   "title": "Lamba Errors (by region)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(account, region) (aws_lambda_errors_sum{function_name=~\".*log-distributor\"})",
     "legendFormat": "{{region}} / {{account}}"
    }
   ]
  },
  { "title": "Lambda Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "S3 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "S3 Delivery Metrics ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(tenant, region) (hcplf_logforwarding_log_count_s3_successful_delivery_sum)",
     "legendFormat": "Success / {{tenant}} / {{region}}"
    },
    {
     "expr": "sum by(tenant, region) (hcplf_logforwarding_log_count_s3_failed_delivery_sum)",
     "legendFormat": "Failure / {{tenant}} / {{region}}"
    }
   ]
  },
  { "title": "CloudWatch Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CloudWatch Event Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(tenant, region) (hcplf_logforwarding_log_count_cloudwatch_successful_events_sum)",
     "legendFormat": "Success / {{tenant}} / {{region}}"
    },
    {
     "expr": "sum by(tenant, region) (hcplf_logforwarding_log_count_cloudwatch_failed_events_sum)",
     "legendFormat": "Failure / {{tenant}} / {{region}}"
    }
   ]
  },
  {
   "title": "CloudWatch Delivery Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(tenant, region) (hcplf_logforwarding_log_count_cloudwatch_successful_delivery_sum)",
     "legendFormat": "Success / {{tenant}} / {{region}}"
    },
    {
     "expr": "sum by(tenant, region) (hcplf_logforwarding_log_count_cloudwatch_failed_delivery_sum)",
     "legendFormat": "Failure / {{tenant}} / {{region}}"
    }
   ]
  }
 ]
}