apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    # Required for Vector to collect logs from this namespace
    hypershift.openshift.io/hosted-control-plane: "true"
