apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-logs
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: vector
        image: vector-collector:github-actions
        env:
        # Set environment variables for testing
        - name: CLUSTER_ID
          value: "test-cluster"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret-key
        # Override resource requests/limits for testing
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"