apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fake-log-generator-github-overlay

resources:
- multi-tenant-setup.yaml

labels:
- includeSelectors: true
  pairs:
    testing.environment: github-actions