apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fake-log-generator-base

resources:
- namespaces.yaml
- deployments.yaml

labels:
- includeSelectors: true
  pairs:
    app: fake-log-generator
    app.kubernetes.io/name: fake-log-generator
    app.kubernetes.io/part-of: multi-tenant-logging
    app.kubernetes.io/component: log-generator